package kr.co.hconnect.polihealth_sdk_android_v2

enum class ProtocolType {
    PROTOCOL_1,
    PROTOCOL_1_ERROR,
    PROTOCOL_2,
    PROTOCOL_2_ERROR_LACK_OF_DATA,
    PROTOCOL_2_ERROR,
    PROTOCOL_2_START,
    PROTOCOL_3_HR_SpO2,
    PROTOCOL_3_HR_SpO2_ERROR,
    PROTOCOL_4_SLEEP_START,
    PROTOCOL_4_SLEEP_START_ERROR,
    PROTOCOL_5_SLEEP_END,
    PROTOCOL_5_SLEEP_END_ERROR,
    PROTOCOL_6,
    PROTOCOL_6_ERROR,
    PROTOCOL_7,
    PROTOCOL_7_ERROR,
    PROTOCOL_8,
    PROTOCOL_8_ERROR,
    PROTOCOL_9_HR_SpO2,
    PROTOCOL_9_ERROR,

    /** Protocol 02 패킷이 기대 길이보다 짧게(잘려서) 수신됨 — BLE MTU 미협상 등 연결 문제로 해당 회차 데이터를 쓸 수 없음 */
    PROTOCOL_2_ERROR_PACKET_TRUNCATED,
}