storePassword=hconnect2025
keyPassword=hconnect2025
keyAlias=polihealth-sdk-android
storeFile=/Users/gwagmin-u/Documents/0_workspace/aos/bluetoothlib/bluetooth-sdk-android-v2/polihealth-sdk-android-v2-example/signature/polihealth-sdk-android-v2-example
